### ISSUE TITLE
"infinite plugin doesn't work"

### ISSUE THREAD

**Issue by taffarelemilio** [brainhubeu/react-carousel#728]
If 'infinite' is active, the carousel disapeears on scroll.

**Comment by morsaken** [comment]
when using the "infinite" plugin, it works but this error throws:

```
react-dom.development.js?61bb:67 Warning: Cannot update a component (`re`) while rendering a different component (`wi`). To locate the bad setState() call inside `wi`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at wi (webpack-internal:///./node_modules/@brainhubeu/react-carousel/lib/react-carousel.js:2:120926)
    at u (webpack-internal:///./node_modules/@brainhubeu/react-carousel/lib/react-carousel.js:2:93945)
    at i (webpack-internal:///./node_modules/@brainhubeu/react-carousel/lib/react-carousel.js:2:125859)
    at withResizeDetector(undefined)
    at Ri (webpack-internal:///./node_modules/@brainhubeu/react-carousel/lib/react-carousel.js:2:128466)
    at RecoilRoot (webpack-internal:///./node_modules/@brainhubeu/react-carousel/lib/react-carousel.js:2:64605)
```
